### ISSUE TITLE
Empty parameters.yaml causes failure

### ISSUE THREAD

**Issue by JaapSingh** [rohitramu/kpm#1]
When parameters.yaml is left blank and a user parameter file is specified via "-f", kpm run fails with stack trace:
```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/rohitramu/kpm/subcommands/common.GetTemplateInput(0xc000072ce0, 0x16, 0xc00009eab0, 0x21, 0xc0001a0540, 0xc0000a0248, 0x0, 0x0, 0x0)
        C:/Users/roramu/go/src/github.com/rohitramu/kpm/subcommands/common/common.go:92 +0x5a4
github.com/rohitramu/kpm/subcommands/common.GetDependencyTree(0xc000072ce0, 0x16, 0xc000072180, 0x1b, 0xc00009e5ec, 0x5, 0x74d392, 0x9, 0xc00009e7b0, 0x21, ...)
        C:/Users/roramu/go/src/github.com/rohitramu/kpm/subcommands/common/dependency_tree.go:264 +0x56b
github.com/rohitramu/kpm/subcommands.RunCmd(0xc000061000, 0x0, 0xc0000611a0, 0x0, 0x0, 0x0, 0x0, 0x74c22d, 0x5)
        C:/Users/roramu/go/src/github.com/rohitramu/kpm/subcommands/run.go:106 +0x9fb
main.main.func6(0xc0000ae6e0, 0xc0000b8200, 0xc0000ae6e0)
        C:/Users/roramu/go/src/github.com/rohitramu/kpm/main.go:202 +0x1af
github.com/urfave/cli.HandleAction(0x6f6660, 0x761c20, 0xc0000ae6e0, 0x0, 0xc0000a8d80)
        C:/Users/roramu/go/src/github.com/urfave/cli/app.go:502 +0xc5
github.com/urfave/cli.Command.Run(0x74bc54, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x75214f, 0x17, 0x0, ...)
        C:/Users/roramu/go/src/github.com/urfave/cli/command.go:165 +0x48e
github.com/urfave/cli.(*App).Run(0xc0000ce1c0, 0xc0000a6000, 0x5, 0x8, 0x0, 0x0)
        C:/Users/roramu/go/src/github.com/urfave/cli/app.go:259 +0x6ea
main.main()
        C:/Users/roramu/go/src/github.com/rohitramu/kpm/main.go:283 +0xe41
```
Fix needs to be made in common.go line 89 to create a new map if default is nil.

**Comment by rohitramu** [comment]
Solved with commit 84f17a841d5e6528401084b83a0d559838cf039a.
